version: '3.9'

volumes:
  init-db:
  data-db:

services:
  mongodb:
    env_file:
      .env
    image: mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    ports:
      - 27017:27017



  web:
    env_file:
      .env
    image: planet_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    build:
      .
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb

  # migration:
  #   build: .
  #   image: app
  #   command: python manage.py migrate
  #   volumes:
  #     - .:/django_mongodb_docker
  #   links:
  #     - mongodb
  #   depends_on:
  #     - make_migrations

  # make_migrations:
  #   build: .
  #   image: app
  #   command: python manage.py makemigrations
  #   volumes:
  #     - .:/django_mongodb_docker
  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb